/**
 * Export gap analysis results as a downloadable file.
 */

function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

function formatDate() {
  return new Date().toISOString().slice(0, 10)
}

export function exportGapsAsMarkdown(gapAnalysis, gapSuggestions) {
  const date = formatDate()
  const lines = [
    `# ResearchGap AI — Research Gap Report`,
    `> Generated on ${date}`,
    ``,
    `## Summary`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
  ]

  if (gapAnalysis) {
    lines.push(`| Total Possible Pairs | ${gapAnalysis.total_possible_pairs} |`)
    lines.push(`| Observed Pairs | ${gapAnalysis.observed_pairs} |`)
    lines.push(`| Research Gaps Found | ${gapAnalysis.missing_pairs} |`)
  }

  lines.push(``, `---`, ``)

  if (gapAnalysis?.top_gaps?.length > 0) {
    lines.push(`## Top Gap Candidates`, ``)
    gapAnalysis.top_gaps.forEach((gap, i) => {
      lines.push(
        `### ${i + 1}. ${gap.method} × ${gap.domain}`,
        `- **Score:** ${gap.score?.toFixed(0)}`,
        `- **Method frequency:** ${gap.method_frequency} papers`,
        `- **Domain frequency:** ${gap.domain_frequency} papers`,
        ``
      )
    })
  }

  if (gapSuggestions?.suggestions?.length > 0) {
    lines.push(`---`, ``, `## AI-Generated Research Opportunities`, ``)
    gapSuggestions.suggestions.forEach((s, i) => {
      lines.push(
        `### ${i + 1}. ${s.method} × ${s.domain}`,
        ``,
        `> ${s.suggestion}`,
        ``,
      )
      if (s.method_papers?.length > 0) {
        lines.push(`**Method papers:** ${s.method_papers.join('; ')}`, ``)
      }
      if (s.domain_papers?.length > 0) {
        lines.push(`**Domain papers:** ${s.domain_papers.join('; ')}`, ``)
      }
      lines.push(`---`, ``)
    })
  }

  lines.push(`*Report generated by ResearchGap AI*`)
  downloadFile(lines.join('\n'), `research-gaps-${date}.md`, 'text/markdown')
}

export function exportGapsAsJSON(gapAnalysis, gapSuggestions) {
  const data = {
    generated_at: new Date().toISOString(),
    summary: gapAnalysis
      ? {
          total_possible_pairs: gapAnalysis.total_possible_pairs,
          observed_pairs: gapAnalysis.observed_pairs,
          missing_pairs: gapAnalysis.missing_pairs,
        }
      : null,
    gap_candidates: gapAnalysis?.top_gaps ?? [],
    ai_suggestions: gapSuggestions?.suggestions ?? [],
  }
  downloadFile(JSON.stringify(data, null, 2), `research-gaps-${formatDate()}.json`, 'application/json')
}
